"""
ethics.py  —  Ethical AI Analysis
====================================
Covers all mandatory ethical considerations from the project brief:
  1. Bias in Dataset
  2. Class Imbalance
  3. Fairness Concerns
  4. Data Privacy
  5. Risk of Misuse
  6. Deployment Risks

Run:
    python ethics.py
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

from data_generator import generate_machine_data, add_fault_events

# ── 0. Load Data ──────────────────────────────────────────────────────────────
df = generate_machine_data(n_samples=500)
df = add_fault_events(df)

FEATURES = ['rpm', 'temperature', 'vibration', 'load', 'pressure']
BG   = '#1a1d27'
TEXT = '#A0AEC0'

print("=" * 65)
print("  ETHICAL AI ANALYSIS — Predictive Cyber Digital Twin")
print("=" * 65)

# ══════════════════════════════════════════════════════════════════════
# 1. BIAS IN DATASET
# ══════════════════════════════════════════════════════════════════════
print("\n[1] BIAS IN DATASET")
print("─" * 55)

# Check distribution skewness
for feat in FEATURES:
    skew = df[feat].skew()
    kurt = df[feat].kurtosis()
    print(f"  {feat:<14} | Skewness: {skew:+.3f} | Kurtosis: {kurt:+.3f}")

print("""
  ANALYSIS:
  ▸ The dataset is SYNTHETIC — generated by code, not collected
    from a real machine. This introduces a form of sampling bias:
    the model only learns the specific mathematical relationships
    we programmed (e.g., temp = 40 + 0.015×RPM + 0.30×Load).

  ▸ Real machines have non-linear wear effects, environmental
    temperature, humidity, and machine aging — none of which
    are captured here.

  ▸ Fault events (overheating, bearing wear, load surge) are
    injected at specific fixed time steps, so the model is
    trained on idealized, predictable faults — not the messy,
    gradual degradation seen in real industrial settings.

  ▸ MITIGATION: Always validate the model on real sensor data
    before deployment. Treat model outputs as advisory only.
""")

# ══════════════════════════════════════════════════════════════════════
# 2. CLASS IMBALANCE
# ══════════════════════════════════════════════════════════════════════
print("[2] CLASS IMBALANCE (Failure Zones)")
print("─" * 55)

# Define condition zones based on temperature and vibration
def classify_condition(row):
    if row['temperature'] >= 105 or row['vibration'] >= 6.5:
        return 'CRITICAL'
    elif row['temperature'] >= 90 or row['vibration'] >= 4.0:
        return 'WARNING'
    else:
        return 'NORMAL'

df['condition'] = df.apply(classify_condition, axis=1)
cond_counts = df['condition'].value_counts()
cond_pct    = df['condition'].value_counts(normalize=True) * 100

print(f"\n  Condition Distribution:")
for cond, count in cond_counts.items():
    print(f"    {cond:<10}: {count:>4} samples ({cond_pct[cond]:.1f}%)")

print(f"""
  ANALYSIS:
  ▸ Class imbalance is present — CRITICAL events are rare
    (~{cond_pct.get('CRITICAL',0):.0f}% of data) while NORMAL is dominant.
    This reflects real industrial scenarios where failures
    are infrequent by design.

  ▸ Risk: ML models trained on imbalanced data tend to be
    over-confident in predicting the dominant class (NORMAL)
    and may miss early warning signs of failure.

  ▸ Since we use regression (not classification), this is
    partially mitigated — the model predicts continuous
    temperature/vibration values rather than binary labels.

  ▸ MITIGATION: For a classification version, use SMOTE
    (Synthetic Minority Oversampling) or class-weighted loss.
""")

# ══════════════════════════════════════════════════════════════════════
# 3. FAIRNESS CONCERNS
# ══════════════════════════════════════════════════════════════════════
print("[3] FAIRNESS CONCERNS")
print("─" * 55)
print("""
  ▸ This system predicts machine behavior, not human outcomes,
    so traditional protected-attribute fairness (race, gender,
    age) does NOT directly apply.

  ▸ However, fairness concerns emerge at the deployment level:

    - ECONOMIC FAIRNESS: Predictive maintenance systems like
      this are expensive to deploy. Smaller factories or
      industries in developing countries may not afford the
      sensors or compute infrastructure needed, creating a
      technology access disparity.

    - OPERATOR IMPACT: If CRITICAL alerts are false positives,
      operators may be wrongly blamed for machine stoppages,
      creating an unfair accountability burden on workers.

    - VENDOR LOCK-IN: If the digital twin is tightly coupled
      to proprietary sensor hardware, organizations may lose
      independence over their own maintenance decisions.

  ▸ MITIGATION: Open-source the model, document uncertainty
    bounds on predictions, and implement human-in-the-loop
    review before any automated shutdown decisions.
""")

# ══════════════════════════════════════════════════════════════════════
# 4. DATA PRIVACY
# ══════════════════════════════════════════════════════════════════════
print("[4] DATA PRIVACY")
print("─" * 55)
print("""
  ▸ CURRENT PROJECT: Uses only synthetic machine sensor data.
    No personal data is collected or processed. ✅

  ▸ PRODUCTION DEPLOYMENT risks:

    - Industrial sensor streams could reveal production volumes,
      operating schedules, and trade secrets if intercepted.

    - In smart manufacturing (Industry 4.0), sensor data feeds
      may be transmitted over cloud platforms, creating attack
      surfaces.

    - Worker behavior patterns (shift times, manual interventions)
      could be inferred from load/RPM anomaly patterns — raising
      employee surveillance concerns.

  ▸ MITIGATION:
    - Encrypt sensor data in transit (TLS 1.3) and at rest (AES-256)
    - Store data on-premise or in private cloud
    - Anonymize operational metadata before model training
    - Follow GDPR / industrial data governance standards
""")

# ══════════════════════════════════════════════════════════════════════
# 5. RISK OF MISUSE
# ══════════════════════════════════════════════════════════════════════
print("[5] RISK OF MISUSE")
print("─" * 55)
print("""
  ▸ OVER-RELIANCE: Operators may trust AI failure predictions
    blindly without physical inspection, leading to missed faults
    that the model was not trained to detect.

  ▸ FALSE POSITIVES: Unnecessary machine shutdowns cost money
    and disrupt production — a CRITICAL alert triggered
    by a sensor glitch, not a real fault, could halt an entire
    assembly line.

  ▸ FALSE NEGATIVES (more dangerous): A NORMAL prediction when
    the machine is actually degrading could lead operators to
    skip preventive maintenance, resulting in catastrophic failure.

  ▸ ADVERSARIAL INPUT: If sensors are tampered with or send
    corrupted data, the model could be tricked into predicting
    safe operation during an actual fault (Garbage In, Garbage Out).

  ▸ MITIGATION:
    - Always validate AI alerts with physical sensor checks
    - Set conservative thresholds (flag WARNING sooner)
    - Log and audit all predictions with timestamps
    - Implement anomaly detection on sensor inputs themselves
""")

# ══════════════════════════════════════════════════════════════════════
# 6. DEPLOYMENT RISKS
# ══════════════════════════════════════════════════════════════════════
print("[6] DEPLOYMENT RISKS")
print("─" * 55)
print("""
  ▸ DISTRIBUTION SHIFT: The model is trained on a motor/pump
    at specific operating ranges (800–2200 RPM). Deploying on a
    different machine type or operating in extreme climates will
    cause prediction degradation.

  ▸ MODEL STALENESS: Machine behavior changes as components wear
    over months/years. A model trained once will become
    progressively less accurate without periodic retraining.

  ▸ SINGLE POINT OF FAILURE: If the digital twin system crashes,
    operators lose real-time monitoring entirely. A fallback
    manual threshold alarm system must always co-exist.

  ▸ SAFETY-CRITICAL CONTEXT: In industries like aerospace,
    petrochemical, or nuclear, a missed alert can cause
    injuries, deaths, or environmental disasters.
    The system must NOT be the sole safety layer.

  ▸ MITIGATION:
    - Continuous monitoring of model performance (drift detection)
    - Monthly retraining with new operational data
    - Human operator final authority on shutdown decisions
    - Regulatory compliance (ISO 13374 for machine condition monitoring)
    - Redundant hardware alarm systems independent of the AI
""")

# ══════════════════════════════════════════════════════════════════════
# VISUALIZATIONS
# ══════════════════════════════════════════════════════════════════════
fig = plt.figure(figsize=(18, 12))
fig.patch.set_facecolor('#0f1117')
fig.suptitle("Ethical AI Analysis — Predictive Cyber Digital Twin",
             color='white', fontsize=14, fontweight='bold')
gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

def style(ax, title, tc='white'):
    ax.set_facecolor(BG)
    ax.tick_params(colors=TEXT, labelsize=9)
    ax.set_title(title, color=tc, fontsize=11, fontweight='bold')
    for sp in ax.spines.values(): sp.set_edgecolor('#333355')
    ax.grid(True, color='#2a2d3e', linewidth=0.5, alpha=0.7)
    return ax

# 1. Condition distribution (class imbalance)
ax1 = fig.add_subplot(gs[0, 0])
style(ax1, 'Class Imbalance\n(Condition Distribution)', '#FFD740')
cond_order = ['NORMAL', 'WARNING', 'CRITICAL']
cc = ['#66BB6A', '#FFD740', '#EF5350']
vals = [cond_counts.get(c, 0) for c in cond_order]
bars = ax1.bar(cond_order, vals, color=cc, alpha=0.85)
for bar, val in zip(bars, vals):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 3,
             f'{val}\n({val/500*100:.0f}%)', ha='center', color='white', fontsize=10)
ax1.set_ylabel('Sample Count', color=TEXT)
ax1.set_ylim(0, max(vals)*1.2)

# 2. Skewness chart
ax2 = fig.add_subplot(gs[0, 1])
style(ax2, 'Dataset Bias Indicator\n(Feature Skewness)', '#00C8FF')
skews = {f: df[f].skew() for f in FEATURES}
colors_sk = ['#EF5350' if abs(v) > 1 else '#FFD740' if abs(v) > 0.5 else '#66BB6A'
             for v in skews.values()]
bars2 = ax2.bar(skews.keys(), skews.values(), color=colors_sk, alpha=0.85)
ax2.axhline(0, color='white', lw=1, ls='--', alpha=0.5)
ax2.axhline(0.5,  color='#FFD740', lw=1, ls=':', alpha=0.6, label='Moderate skew')
ax2.axhline(-0.5, color='#FFD740', lw=1, ls=':', alpha=0.6)
ax2.set_ylabel('Skewness', color=TEXT)
ax2.legend(facecolor=BG, labelcolor='white', fontsize=8)
for bar, val in zip(bars2, skews.values()):
    ax2.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + (0.015 if val >= 0 else -0.04),
             f'{val:.2f}', ha='center', color='white', fontsize=9)

# 3. Risk matrix
ax3 = fig.add_subplot(gs[0, 2])
ax3.set_facecolor(BG)
ax3.set_title('Risk Matrix\n(Likelihood vs Impact)', color='#EF5350', fontsize=11, fontweight='bold')
for sp in ax3.spines.values(): sp.set_edgecolor('#333355')

risks = [
    ('Over-reliance\non AI', 0.6, 0.8, '#EF5350'),
    ('False\nNegative', 0.4, 0.95, '#EF5350'),
    ('False\nPositive', 0.7, 0.5, '#FFD740'),
    ('Model\nStaleness', 0.5, 0.6, '#FFD740'),
    ('Data\nPrivacy', 0.3, 0.4, '#66BB6A'),
    ('Distribution\nShift', 0.45, 0.7, '#FFD740'),
]
for label, likelihood, impact, color in risks:
    ax3.scatter(likelihood, impact, s=300, color=color, alpha=0.85, zorder=5)
    ax3.annotate(label, (likelihood, impact), textcoords='offset points',
                 xytext=(8, 4), color='white', fontsize=7.5)
ax3.set_xlabel('Likelihood', color=TEXT, fontsize=10)
ax3.set_ylabel('Impact / Severity', color=TEXT, fontsize=10)
ax3.set_xlim(0, 1); ax3.set_ylim(0, 1)
ax3.axhline(0.5, color='#444466', lw=1, ls='--', alpha=0.5)
ax3.axvline(0.5, color='#444466', lw=1, ls='--', alpha=0.5)
ax3.tick_params(colors=TEXT)

# 4. Fault window proportion
ax4 = fig.add_subplot(gs[1, 0])
style(ax4, 'Fault Event Coverage\n(Sampling Bias)', '#AB47BC')
normal_count  = 500 - (21 + 21 + 21)
fault_data = {'Normal\nOperation': normal_count,
              'Overheating\n(t=150-170)': 21,
              'Bearing Wear\n(t=320-340)': 21,
              'Load Surge\n(t=420-440)': 21}
wedge_colors = ['#66BB6A', '#EF5350', '#AB47BC', '#FFD740']
wedges, texts, autotexts = ax4.pie(
    fault_data.values(), labels=fault_data.keys(),
    colors=wedge_colors, autopct='%1.1f%%',
    textprops={'color': TEXT, 'fontsize': 8},
    wedgeprops={'edgecolor': '#0f1117', 'linewidth': 1.5})
for at in autotexts: at.set_color('white')
ax4.set_facecolor(BG)

# 5. Ethics summary text panel
ax5 = fig.add_subplot(gs[1, 1:])
ax5.set_facecolor(BG)
ax5.axis('off')
for sp in ax5.spines.values(): sp.set_edgecolor('#333355')

summary_items = [
    ('🔴', 'Data Bias',       'Synthetic data lacks real-world noise, aging, environmental factors'),
    ('🟡', 'Class Imbalance', f'CRITICAL events = only {cond_pct.get("CRITICAL",0):.0f}% of dataset — model may underdetect failures'),
    ('🟡', 'Fairness',        'No human attributes involved; deployment fairness concern for small industries'),
    ('🟢', 'Data Privacy',    'No personal data used; production must encrypt sensor streams'),
    ('🔴', 'Risk of Misuse',  'False negatives in safety-critical settings could cause physical harm'),
    ('🟡', 'Deployment Risk', 'Model staleness, distribution shift, single-point-of-failure risks'),
]
ax5.set_title('Ethical Risk Summary', color='white', fontsize=11, fontweight='bold', loc='left', pad=12)
for i, (icon, title, desc) in enumerate(summary_items):
    y = 0.88 - i * 0.15
    ax5.text(0.01, y,        icon,  transform=ax5.transAxes, fontsize=13, va='top')
    ax5.text(0.07, y,        title, transform=ax5.transAxes, fontsize=10, color='white',
             fontweight='bold', va='top')
    ax5.text(0.07, y-0.06,   desc,  transform=ax5.transAxes, fontsize=9, color=TEXT, va='top')

plt.savefig("ethics_analysis.png", dpi=150, bbox_inches='tight', facecolor='#0f1117')
plt.close()
print("\n  [Saved] ethics_analysis.png")
print("\n  ✅ Ethical AI analysis complete.")
print("=" * 65)
